development:
  adapter: postgresql
  database: hirviurheilu
  encoding: unicode
  pool: 5

test: &test
  adapter: postgresql
  database: hirviurheilu_test
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  pool: 5

cucumber:
  <<: *test
