development:
  adapter: postgresql
  database: <%= ENV['ELK_SPORTS_DATABASE_NAME'] || 'elk_sports' %>
  encoding: unicode
  pool: 5

test: &test
  adapter: postgresql
  database: elk_sports_test
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  database: elk_sports
  username: elk_sports
  password: elk_sports
  encoding: unicode
  pool: 5

cucumber:
  <<: *test
